#!/usr/bin/env bash

# Call the make on Makefile to build all the binaries for the 5 problems
make all


# =======================
# Problem-1_1: 1D Grid/Block multiplication
# Usage: ./matmul_1d <M> <N> <path to matrix_a.csv> <path to matrix_b.csv>
# Output:
# Product Matrix of size 123 stored as matrix_c.csv
# Kernel execution time: 456 microseconds
# =======================
# =======================
# Problem-1_1: 1D Grid/Block multiplication
# Usage: ./matmul_1d <M> <N> <path to matrix_a.csv> <path to matrix_b.csv>
# Output:
# Product Matrix of size 123 stored as matrix_c.csv
# Kernel execution time: 456 microseconds
# =======================

# Clear old output file
> output_1_1_CS25MTECH11015.txt

# Example sweep of thread blocks (M) and threads per block (N)
for M in 8 16 32; do
  for N in 32 64 128; do
    echo "Trial: GridBlocks=$M ThreadsPerBlock=$N" >> results_1_1.txt
    ./matmul_1d $M $N public_test_cases/matrix_a.csv public_test_cases/matrix_b.csv 
    echo "" >> output_1_1_CS25MTECH11015.txt
  done
done



####
# Report: min 8 data points
# | TrialNo | #Thread Blocks(M) | #Threads in a block(N) | KernelExecution time(microsecs) | Your insights on the execution time |
####








# =======================
# Problem-1_2: 2D Grid/Block multiplication
# Usage: ./matmul_2d <X1> <Y1> <X2> <Y2> <matrix_a.csv> <matrix_b.csv>
# =======================
echo"======================="
echo "Problem-1.2"
echo"======================="

for X1 in 8 16; do
  for Y1 in 8 16; do
    for X2 in 8 16; do
      for Y2 in 8 16; do
        ./matmul_2d $X1 $Y1 $X2 $Y2 public_test_cases/matrix_a.csv public_test_cases/matrix_b.csv 
      done
    done
  done
done


####
# Report
# # | TrialNo | 2D Grid Size(X1, Y1) | 2D Block Size(X2, Y2) | KernelExecution time(microsecs) | Your insights on the execution time |
####



# =======================
# Problem-2: Tiled Multiplication
# Usage: ./matmul_tiled <TILE_WIDTH> <matrix_a.csv> <matrix_b.csv>
# =======================
echo"======================="
echo "Problem-2"
echo"======================="

for TILE_WIDTH in 8 16 32; do
  ./matmul_tiled $TILE_WIDTH public_test_cases/matrix_a.csv public_test_cases/matrix_b.csv >> output_2_CS25MTECH11015.txt
done


####
# Report
# # | TrialNo | #Global Memory Accesses | #Shared Memory Accesses | KernelExecution time(microsecs) | Your insights on the execution time |
####



# =======================
# Problem-3: Basic Transpose
# Usage: ./mattrans_basic <M> <N> <matrix_a.csv>
# =======================
echo"======================="
echo "Problem-3"
echo"======================="

for M in 128 256; do
  for N in 128 256; do
    ./mattrans_basic $M $N public_test_cases/matrix_a.csv >> output_3_CS25MTECH11015.txt
  done
done


####
# Report:
# | TrialNo | #Thread Blocks(M) | #Threads in a block(N) | KernelExecution time(microsecs) | Your insights on the execution time |
####



# =======================
# Problem-4: Tiled Transpose
# Usage: ./mattrans_tiled <TILE_WIDTH> <matrix_a.csv>
# =======================
echo"======================="
echo "Problem-4"
echo"======================="

for TILE_WIDTH in 8 16 32; do
  ./mattrans_tiled $TILE_WIDTH public_test_cases/matrix_a.csv >> output_4_CS25MTECH11015.txt
done


####
# Report
# # | TrialNo | KernelExecution time(microsecs) | Your insights on the execution time |
# Try using the entire shared memory (64KB)
####



# Delete all the binaries generated by make
make clean
